[workspace]
members = [
  "freminal",
  "freminal-buffer",
  "freminal-common",
  "freminal-terminal-emulator",
  "xtask",
]
default-members = [
  "freminal",
  "freminal-buffer",
  "freminal-common",
  "freminal-terminal-emulator",
]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Fred Clausen"]
license = "MIT"
description = "A terminal emulator written in Rust"
repository = "https://github.com/fredclausen/freminal"
documentation = "https://github.com/fred/freminal/README.md"
homepage = "https://github.com/fredclausen/freminal"
readme = "README.md"
rust-version = "1.91.0"
version = "0.1.0"

[workspace.metadata.cargo-machete]
ignored = ["vergen"]

[workspace.dependencies]
anyhow = "1.0.100"
cargo_metadata = "0.23.1"
clap = { version = "4.5.53", features = ["derive"] }
clap-cargo = { version = "0.18.3", features = ["cargo_metadata"] }
clap-verbosity-flag = "3.0.4"
color-eyre = "0.6.5"
conv2 = "0.4.2"
criterion = "0.7.0"
crossbeam-channel = "0.5.15"
directories = "6.0.0"
duct = "1.1.1"
eframe = { version = "0.33.2", default-features = false, features = [
  "default_fonts",
  "glow",
  "persistence",
  "wayland",
  "x11",
] }
egui = { version = "0.33.2", default-features = false, features = [
  "default_fonts",
  "persistence",
] }
fontdb = "0.23.0"
parking_lot = "0.12.4"
portable-pty = "0.9.0"
serde = { version = "1.0.228", features = ["derive"] }
sys-locale = "0.3.2"
tar = "0.4.44"
toml = "0.9.8"
thiserror = "2.0.17"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.20", features = [
  "env-filter",
  "parking_lot",
] }
unicode-segmentation = "1.12.0"
unicode-width = "0.2.2"
test-log = { version = "0.2.18", features = ["trace"] }
tempfile = "3.23.0"
vergen = { version = "9.0.6", features = ["build", "cargo", "rustc", "si"] }

# dev
proptest = "1.9.0"
assert_cmd = "2.1.1"
predicates = "3.1.3"
