[package]
name = "freminal"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.bundle]
name = "Freminal"
identifier = "io.github.fredclausen.freminal"
copyright = "Copyright (c) 2024-2025 Fred Clausen"
category = "Developer Tools"
icon = ["32x32.png", "128x128.png", "128x128@2x.png"]
version = "1.0.0"
resources = ["assets", "images/**/*.png", "secrets/public_key.txt"]
short_description = "A terminal emulator written in Rust"
long_description = """
Freminal is a terminal emulator written in Rust, designed to provide a fast, efficient, and customizable terminal experience. It leverages modern Rust libraries and technologies to deliver a robust and user-friendly interface for developers and power users.
"""
# deb_depends = ["libgl1-mesa-glx", "libsdl2-2.0-0 (>= 2.0.5)"]
# osx_frameworks = ["SDL2"]
osx_url_schemes = ["io.github.fredclausen.freminal"]

[[bin]]
name = "freminal"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe.workspace = true
egui.workspace = true
conv2.workspace = true
anyhow.workspace = true
fontdb.workspace = true
parking_lot.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
freminal-terminal-emulator = { path = "../freminal-terminal-emulator" }
freminal-common = { path = "../freminal-common" }

# dev dependencies
[dev-dependencies]
criterion.workspace = true

[features]
default = []
validation = []

[[bench]]
name = "render_loop_bench"
harness = false
